config/routes.rb
Rails.application.routes.draw do
  get 'products/renewable_energy'

  get 'products/environment_care'

  get 'products/metal_forming'

  get 'welcome/index'

  root 'welcome#index'

  post 'welcome/send_mail'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def renewable_energy
  end

  def environment_care
  end

  def metal_forming
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def send_mail
  #  puts RestClient.post("https://api:#{ENV['MAILGUN_API_SHRESTHA']}"\
  #  "@api.mailgun.net/v3/shresthasolutions.com/messages",
  #  :from => "Shrestha Site <mailgun@shresthasolutions.com>",
  #  :to => "jay2452@live.com, jayantt@hotmail.com, jayant2452@gmail.com",
  #  :subject => "Contact Enquirey",
  #  :text => "Name: #{params["name"]}\nEmail : #{params[:email]} \n #{params["comments"]}")

    if verify_recaptcha
        ContactMailer.contact_notification(params[:name], params[:email], params[:comments]).deliver
    end


   redirect_to :back, notice: "Sent !!, we will be contacting you shortly"



  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shrestha Solutions</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">

    <meta name="description" content="shrestha solutions , shresthasolutions.com, shresthasolutions, shrestha solutions bbsr, shrestha solutions bhubaneswar,shrestha solutions odisha, shrestha solution,  renawable energy setting" />

     <meta name="keywords" content="shrestha solutions , shresthasolutions.com, shresthasolutions, shrestha solutions bbsr, shrestha solutions bhubaneswar,shrestha solutions odisha, shrestha solution,  renawable energy setting" />
     <meta name="robots" content="index, follow"/>

  </head>

  <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
    <%= yield %>

    <footer class="container-fluid text-center">
      <a href="#myPage" title="To Top">
        <span class="glyphicon glyphicon-chevron-up"></span>
      </a>

      <p>
        Site Developed and Maintained by <a href="http://www.innovadorslab.com" target="_blank"> Innovadors Lab</a>
      </p>
    </footer>

  </body>
</html>

app/views/products/_nav_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>" data-turbolinks="false">Shrestha Solutions</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="/#about">ABOUT</a></li>
        <li><a href="/#services">SERVICES</a></li>
        <li><a href="/#products">PRODUCTS</a></li>
        <li><a href="/#contact">CONTACT</a></li> -->
        <li><%= link_to "Back", :back, :"data-turbolinks" => "false" %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/products/environment_care.html.erb
<%= render 'products/nav_bar' %>


<div class="container-fluid">
  <h2 class="text-center">Environment Care Products</h3>
  <div class="container-fluid">
    <div class="col-md-8"> <br> <br>
      <h4>
        <ul>
          <li>BIO GAS PLANT ORGANIC WASTE BASED</li>
          <li>SOLID WASTE MANAGEMENT  & DISPOSALS </li>
          <li>SEWAGE TREATMENT PLANTS</li>
          <li>LOW COST DRINKING WATER TREATMENT PLANTS</li>
        </ul>
      </h4>
    </div>

    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha21" %>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha4" %>
      </div>
    </div>

    <div class="col-md-8">
        <br>
        <h4>
          <ul>
            <li>GROUND WATER RECHARGING SYSTEMS</li>
            <li>OZONE GENERATORS FOR WATER STERILIZATION</li>
            <li>ROOFTOP GARDEN COMPLETE WITH AUTO / MANUAL WATERING PROVISION AND PREPARED SOIL</li>
            <li>ELECTRICAL / FUEL ENERGY CONSERVATION METHODS INCLUDING ENERGY AUDITS</li>
          </ul>
        </h4>
    </div>
  </div>

</div>

app/views/products/metal_forming.html.erb
<%= render 'products/nav_bar' %>



<div class="container-fluid">
  <h2 class="text-center">Metal Forming and Fabrications Products</h2>
  <div class="row">
    <div class="col-md-8"> <br> <br>
      <h4>
        <ul>
          <li>METAL DOOR FRAMES, WINDOW FRAMES FOR HOUSES</li>
          <li>ELECTRICAL PANELS  (POWER, CONTROL AND AUTOMATIONS, SUB-STATION, SOLAR)</li>
          <li>LIGHT WEIGHT METAL DOORS WITH NATURAL FINISH</li>
        </ul>
      </h4>
    </div>

    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha31" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha6" %>
      </div>
    </div>

    <div class="col-md-8"> <br>
      <h4>
        <ul>
          <li>METAL UTILITY STRUCTRE SUCH AS – BED, SOLAR PANEL STRUCTURES, ROOFTOP GARDEN TRAY STANDS,
            SHADOW MAKING FRAMES</li>
          <li>SS HIGH QUALITY INNOVATIVE HOSPITAL FURNITURES</li>
          <li>METAL SEWAGE TANKS FOR BIOLOGICAL TREATMENT OF WASTE WATER</li>
        </ul>
      </h4>
    </div>
  </div>

</div>

app/views/products/renewable_energy.html.erb
<%= render 'products/nav_bar' %>

<div class="container-fluid">
  <h2 class="text-center">Renewable Energy Products</h2>
  <div class="row">
    <div class="col-md-8"> <br><br>
      <h4>
        <ul>
          <li>SOLAR WATER PUMPING SYSTEMS</li>
        </ul>
      </h4>
    </div>

    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha1" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha7" %>
      </div>
    </div>

    <div class="col-md-8"> <br> <br>
      <h4>
        <ul>
          <li>SOLAR WATER HEATERS</li>
        </ul>
      </h4>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8"> <br> <br>
      <h4>
        <ul>
          <li>SOLAR POWER BANK FOR DOMESTIC AND COMMERCIAL BUILDINGS</li>
          <li>SOLAR DRYERS FOR INDUSTRIES , SMALL  BUSINESS HOUSE</li>
        </ul>
      </h4>
    </div>

    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha8" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <%= image_tag "shrestha9" %>
      </div>
    </div>

    <div class="col-md-8"> <br> <br>
      <h4>
        <ul>
          <li>BIO GAS PLANTS</li>
          <li>WIND POWER STATIONS</li>
        </ul>
      </h4>
    </div>
  </div>

</div>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>" data-turbolinks="false">Shrestha Solutions</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#about">ABOUT</a></li>
        <li><a href="#services">SERVICES</a></li>
        <li><a href="#products">PRODUCTS</a></li>
        <li><a href="#contact">CONTACT</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="jumbotron text-center" style="background-color: #0f9e00;">
  <h1>Shrestha Solutions</h1>
  <p>
    We specialize in Renewable Energy, Environmental Care & Metal and Fabrications Products
  </p>
</div>

<div class="container-fluid" id="about">
  <div class="row">
    <div class="col-sm-8">
      <h2>About Company</h2>
      <h4>
        To provide complete solutions for different activities in the field of power, energy and
        environment SHRESTHA SOLUTIONS was established. It is providing services
        since last 15 years to customers. It is backed up by qualified engineers and
        professionals to stand with all solutions. Coming across many crisis, problems from
        various organizations and individuals ; We have developed sustainable solutions
        with most appropriate technologies. We study, consult and provide selective
        solutions in our field to bring complete satisfactions among our customers.
      </h4>
      <!-- <button class="btn btn-default btn-lg">Get in Touch</button> -->
      <a href="#contact" class="btn btn-default btn-lg">Get in Touch</a>
    </div>
    <div class="col-sm-4 text-center">
      <span class="glyphicon glyphicon-signal logo"></span>
    </div>
  </div>
</div>

<div class="container-fluid bg-grey text-center slideanim" id="services">
  <h2 class="h2 text-uppercase">services</h2>
  <h4>What we offer</h4> <br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>ENERGY CONSERVATION METHOD IMPLEMENTATION</h4>
    </div>

    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>ENERGY AUDITING</h4>
    </div>

    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>ELECTRICAL & FIRE SAFETY AUDIT</h4>
    </div>
  </div>
  <br><br>
  <div class="row">
    <div class="col-sm-6">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4>ELECTRICAL INSTALLATION AND TESTING</h4>
    </div>

    <div class="col-sm-6">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>COMPLETE INSTALLATION OF ROOFTOP GARDENS</h4>
    </div>

  </div>

</div>

<div class="container-fluid text-center slideanim" id="products">
  <h2>Products</h2>
  <div class="row text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <a href="<%= products_renewable_energy_path %>" data-turbolinks="false">
          <%= image_tag("shrestha1", alt: "solar water pumping systems") %>
          <p><strong class="text-uppercase">renewable energy</strong></p>
        </a>
        <p>We have many projects related to renewable energy.</p>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="thumbnail">
        <a href="<%= products_environment_care_path %>" data-turbolinks="false">
          <%= image_tag("shrestha21", alt: "Bio gas plant") %>
          <p><strong class="text-uppercase">environment care</strong></p>
        </a>
        <p>Our environment friendly products.</p>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="thumbnail">
        <a href="<%= products_metal_forming_path %>" data-turbolinks="false">
          <%= image_tag("shrestha31", alt: "Metal Forming and Fabrications") %>
          <p><strong class="text-uppercase">Metal forming and Fabrications</strong></p>
        </a>
        <p>We have a large variety of products in metal forming and fabrications.</p>
      </div>
    </div>
  </div>

</div>

<div class="container-fluid bg-grey slideanim" id="contact">
  <h2 class="text-center">CONTACT</h2> <br>
  <div class="row">
    <div class="col-sm-5">
      <p>
        Contact us and we'll get back to you within 24 hours
      </p>
      <p><span class="glyphicon glyphicon-map-marker"></span>
        SHRESTHA SOLUTIONS <br> 1242/5, ANAND NAGAR, BOMIKHAL <br> BHUBANESWAR – 751010
        <br>
        <span class="glyphicon glyphicon-map-marker"></span> Works : A – 8, Mancheswar Industrial Estate, Bhubaneswar – 751010
      </p>
      <p><span class="glyphicon glyphicon-phone"></span> +919861040136 / +919437256345</p>
      <p><span class="glyphicon glyphicon-envelope"></span>
        nihar_ic@yahoo.com
      </p>
    </div>
    <div class="col-sm-7">
      <div class="row">

        <%= form_tag welcome_send_mail_path, method: :post do  %>
          <div class="col-sm-6">
            <div class="form-group">
              <%= text_field_tag :name, nil, {placeholder: "Name", required: true, class: "form-control"} %>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="form-group">
              <%= email_field_tag :email, nil, {placeholder: "Email", required: true, class: "form-control"} %>
            </div>
          </div>

          <div class="col-sm-12 form-group">
            <%= text_area_tag :comments, nil, {placeholder: "Comments", required: true, class: "form-control", rows: "6"} %>
          </div>

          <div class="col-sm-12 form-group">
            <div class="row">
              <div class="col-sm-6">
                <%= recaptcha_tags %>
              </div>
              <div class="col-sm-6">
                <%= submit_tag "Send", class: "btn btn-default btn-lg pull-right" %>
              </div>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>